---
on:
  push
  #schedule:
  #  - cron: '* */3 * * *'
jobs:
  mirror-w1hkj:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v3
    #  with:
    #    repository: bhcleek/git-mirror
    #    ref: v1.0.0-beta.1
    #    token: ${{ secrets.SF_SYNC }}
    #    path: ./
    #    persist-credentials: false
    - name: mirror-fldigi
      uses: bhcleek/git-mirror@v1.0.0-beta.9
      #continue-on-error: true
      with:
        source_repo: "https://git.code.sf.net/p/fldigi/fldigi"
        destination_repo: "bhcleek/fldigi"
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        destination_ssh_private_key: "${{ secrets.SF_FLNET }}"
